
SHELL = /bin/sh

include ${PETSC_DIR}/${PETSC_ARCH}/conf/petscvariables
include ${PETSC_DIR}/conf/variables
include ${DENDRO_DIR}/makeVariables
PCC = mpicxx

CEXT = C

CFLAGS = -g -fast
# -D_COMPUTE_EXACT
# -openmp
# -DPETSC_USE_LOG 
include ./makefileCore



