
SHELL = /bin/sh

include ${PETSC_DIR}/${PETSC_ARCH}/conf/petscvariables
include ${PETSC_DIR}/conf/variables
include ${DENDRO_DIR}/makeVariables
PCC = mpicxx

CEXT = C

CFLAGS = -DPETSC_USE_LOG 

# -fast 
# -D_WRITE_SOLN 
# -D_COMPUTE_EXACT
# -DDEBUG
# -openmp


include ./makefileCore



