
SHELL = /bin/sh

include ${PETSC_DIR}/${PETSC_ARCH}/conf/petscvariables
include ${PETSC_DIR}/conf/variables
include ${DENDRO_DIR}/makeVariables

CEXT = C

CFLAGS = -DPETSC_USE_LOG  -O3 

#-DUSE_TENSOR 

include ./makefileCore

